openapi: 3.0.0
info:
  title: Chat and Rooms API
  version: 1.0.0
paths:
  /api/rooms:
    get:
      summary: Get all rooms
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    createdBy:
                      type: string
                    chat:
                      type: object
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              username:
                                type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
    post:
      summary: Create a new room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - chatId
              properties:
                name:
                  type: string
                chatId:
                  type: string
      responses:
        "200":
          description: Room created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  createdBy:
                    type: string
                  chatId:
                    type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/chat/{chatId}/message-list:
    get:
      summary: Get message list for a chat
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        content:
                          type: string
                        createdAt:
                          type: string
                        sender:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            username:
                              type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/chat/all-chats:
    get:
      summary: Get all chats for authenticated user
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              username:
                                type: string
                    messages:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          content:
                            type: string
                          createdAt:
                            type: string
                          sender:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              username:
                                type: string
                    group:
                      type: object
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/chat/private-chat:
    post:
      summary: Create or get existing private chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                memberIds:
                  type: array
                  items:
                    type: string
      responses:
        "200":
          description: Existing chat found
          content:
            application/json:
              schema:
                type: object
        "201":
          description: Chat created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            username:
                              type: string
                  messages:
                    type: array
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/chat/send-message:
    post:
      summary: Send a message to a chat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                chatId:
                  type: string
                content:
                  type: string
      responses:
        "200":
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  content:
                    type: string
                  senderId:
                    type: string
                  chatId:
                    type: string
                  createdAt:
                    type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/chats:
    get:
      summary: Get all chats for authenticated user
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    type:
                      type: string
                    members:
                      type: array
                      items:
                        type: object
                        properties:
                          user:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              username:
                                type: string
                    messages:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: string
                          content:
                            type: string
                          createdAt:
                            type: string
                          sender:
                            type: object
                            properties:
                              id:
                                type: string
                              name:
                                type: string
                              username:
                                type: string
                    group:
                      type: object
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
  /api/users:
    get:
      summary: Search users
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    username:
                      type: string
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
